name: Continuous Integration Pull Request

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    name: Add PR Labels
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-24.04

    steps:
      - name: Add Folder Labels
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  lint-pr:
    permissions:
      contents: read
      pull-requests: write

    name: Lint Pull Request
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v6.2.1

      - name: Lint Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: npx danger ci --failOnErrors --text-only
