name: Continuous Integration Pull Request

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
      - milestoned
      - demilestoned

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write

    name: Add PR Labels
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Add Folder Labels
        uses: actions/labeler@v5

  lint-pr:
    permissions:
      contents: read
      pull-requests: write

    name: Lint Pull Request
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: npx danger ci --failOnErrors --text-only
