name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

  lint:
    name: Lint Code
    needs: dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Lint Code
        run: npm run lint

  build:
    name: Build Code
    needs: dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Build Code
        run: npm run build
