name: Continuous Integration

on:
  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v6

  build:
    name: Build Code
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Code
        run: npm run build

  test:
    name: Test Code
    runs-on: ubuntu-24.04

    env:
      NODE_ENV: test

    steps:
      - name: Set Up ENV
        run: |
          echo "NODE_ENV=$NODE_ENV" >> .env

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Shared
        run: npm run build:shared

      - name: Test Code
        run: npm run test:unit
