name: Integration Tests

on:
  workflow_call:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api-integration:
    name: Test API Integration
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    env:
      NODE_ENV: test

    steps:
      - name: Set Up ENV
        run: |
          echo "NODE_ENV=$NODE_ENV" >> .env
          echo "API_BASE_URL=${{ secrets.DEVELOPMENT_API_BASE_URL }}" >> .env

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Extract Playwright Version
        id: extract-playwright-version
        run: echo "version=$(jq -r '.devDependencies[\"@playwright/test\"]' package.json)" >> $GITHUB_OUTPUT

      - name: Build Shared Package
        run: npm run build:shared

      - name: Run Tests
        run: npm run test:integration

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report
          path: tests/test-report/
          retention-days: 30
